name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_interpreter }}
  - click
  - sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  # - jupyter
  # - ipython
# Include pip based packages
  # - pip:
  #   - sklearn-pandas
  #   - imbalanced-learn
