name: {{ cookiecutter.short_prj_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_interpreter }}
  - click
  - sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  # Some packages you're likly going to need
  # - pandas
  # - numpy
  # - matplotlib
  # - engarde
  # - jupyter
  # - ipython
# Include pip based packages
  - pip:
    - -e .
    # - sklearn-pandas
  #   - imbalanced-learn
